use std::sync::LazyLock;

use async_trait::async_trait;
use regex::Regex;
use tracing::debug;

use crate::skill_resolver::LoadedAgentSkill;

static THINK_TAG_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)<think(?:ing)?>.*?</think(?:ing)?>").expect("valid think-tag regex"));

static LOAD_SKILL_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)\[LOAD_SKILL:\s*([^\]]+)\]").expect("valid load-skill regex"));

/// Remove `<think>...</think>` and `<thinking>...</thinking>` tags from text.
pub fn strip_think_tags(text: &str) -> String {
    THINK_TAG_RE.replace_all(text, "").into_owned()
}

pub fn detect_skill_load_requests(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    for cap in LOAD_SKILL_RE.captures_iter(text) {
        let Some(name) = cap.get(1).map(|m| m.as_str().trim()) else {
            continue;
        };
        if name.is_empty() || names.iter().any(|existing| existing == name) {
            continue;
        }
        names.push(name.to_owned());
    }
    names
}

pub fn has_skill_load_requests(text: &str) -> bool {
    LOAD_SKILL_RE.is_match(text)
}

#[async_trait]
pub trait ISkillLoadService: Send + Sync {
    async fn load_skill_bodies(&self, names: &[String]) -> Vec<LoadedAgentSkill>;
}

/// Result of message middleware processing.
#[derive(Debug, Clone)]
pub struct MiddlewareResult {
    /// The processed message content with private thinking tags stripped.
    pub message: String,
    /// Optional display-only message.
    pub display_message: Option<String>,
    /// System responses generated by middleware side effects.
    pub system_responses: Vec<String>,
}

/// Post-processing pipeline for completed agent messages.
pub struct MessageMiddleware {
    skill_loader: Option<Box<dyn ISkillLoadService>>,
}

impl MessageMiddleware {
    pub fn new() -> Self {
        Self { skill_loader: None }
    }

    pub fn new_with_skill_loader(skill_loader: Option<Box<dyn ISkillLoadService>>) -> Self {
        Self { skill_loader }
    }

    /// Process a completed agent message through the middleware pipeline.
    pub async fn process(&self, message: &str, _user_id: &str, _conversation_id: &str) -> MiddlewareResult {
        let cleaned = strip_think_tags(message);
        let skill_names = detect_skill_load_requests(&cleaned);
        let system_responses = self.load_requested_skills(&skill_names).await;

        MiddlewareResult {
            message: cleaned,
            display_message: None,
            system_responses,
        }
    }

    async fn load_requested_skills(&self, names: &[String]) -> Vec<String> {
        if names.is_empty() {
            return Vec::new();
        }

        let Some(skill_loader) = &self.skill_loader else {
            debug!(
                count = names.len(),
                "Skill load requests detected but no skill loader configured"
            );
            return Vec::new();
        };

        let loaded = skill_loader.load_skill_bodies(names).await;
        if loaded.is_empty() {
            return Vec::new();
        }

        loaded
            .into_iter()
            .map(|skill| format!("[Skill: {}]\n{}", skill.name, skill.body))
            .collect()
    }
}

impl Default for MessageMiddleware {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_think_tags_basic() {
        let input = "Before<think>internal thought</think>After";
        assert_eq!(strip_think_tags(input), "BeforeAfter");
    }

    #[test]
    fn strip_thinking_tags_basic() {
        let input = "<thinking>deep reasoning</thinking>Answer here";
        assert_eq!(strip_think_tags(input), "Answer here");
    }

    #[test]
    fn strip_think_tags_multiline() {
        let input = "Start\n<think>\nline 1\nline 2\n</think>\nEnd";
        assert_eq!(strip_think_tags(input), "Start\n\nEnd");
    }

    #[test]
    fn strip_think_tags_none() {
        let input = "No tags here at all.";
        assert_eq!(strip_think_tags(input), "No tags here at all.");
    }

    #[test]
    fn detect_skill_load_requests_is_case_insensitive_and_dedupes() {
        let requests = detect_skill_load_requests("[load_skill: cron] [LOAD_SKILL: cron] [LOAD_SKILL: pdf]");
        assert_eq!(requests, vec!["cron", "pdf"]);
    }

    #[tokio::test]
    async fn middleware_loads_requested_skills() {
        struct MockSkillLoader;

        #[async_trait]
        impl ISkillLoadService for MockSkillLoader {
            async fn load_skill_bodies(&self, names: &[String]) -> Vec<LoadedAgentSkill> {
                names
                    .iter()
                    .map(|name| LoadedAgentSkill {
                        name: name.clone(),
                        body: format!("body for {name}"),
                    })
                    .collect()
            }
        }

        let mw = MessageMiddleware::new_with_skill_loader(Some(Box::new(MockSkillLoader)));
        let result = mw.process("Need [LOAD_SKILL: cron]", "user", "conv").await;

        assert_eq!(result.message, "Need [LOAD_SKILL: cron]");
        assert_eq!(result.system_responses, vec!["[Skill: cron]\nbody for cron"]);
    }
}
