use std::time::{Duration, Instant};

use tokio::sync::mpsc;

/// Unique identifier for a WebSocket connection.
///
/// Generated by `AtomicU64` counter in `WebSocketManager`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ConnectionId(pub u64);

impl std::fmt::Display for ConnectionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "conn-{}", self.0)
    }
}

/// Outbound message for a WebSocket connection.
///
/// Sent through the per-connection `mpsc` channel to the send loop.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WsOutbound {
    /// UTF-8 text frame.
    Text(String),
    /// Close frame with status code and reason.
    Close(WebSocketCloseCode, String),
    /// UTF-8 text frame followed immediately by a close frame.
    TextThenClose(String, WebSocketCloseCode, String),
}

/// WebSocket close codes per RFC 6455.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum WebSocketCloseCode {
    /// 1000 — normal closure.
    NormalClosure = 1000,
    /// 1008 — policy violation (auth failure, heartbeat timeout).
    PolicyViolation = 1008,
}

impl WebSocketCloseCode {
    /// Return the numeric close code.
    pub fn as_u16(self) -> u16 {
        self as u16
    }
}

/// Realtime transport/envelope boundary errors.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RealtimeError {
    /// Authentication token is missing.
    AuthMissing,
    /// Authentication token is expired or no longer valid.
    AuthExpired,
    /// Incoming message did not match the standard WebSocket envelope.
    InvalidMessage,
    /// Incoming message used a valid envelope but no realtime route supports it.
    UnsupportedMessage,
    /// Connection missed the heartbeat deadline and will be closed.
    HeartbeatTimeout,
    /// Outbound queue is saturated.
    Backpressure,
    /// WebSocket transport write failed.
    SendFailed,
    /// Realtime boundary hit an unexpected internal failure.
    Internal,
}

impl RealtimeError {
    /// Stable machine-readable realtime error code.
    pub fn code(self) -> &'static str {
        match self {
            Self::AuthMissing => "REALTIME_AUTH_MISSING",
            Self::AuthExpired => "REALTIME_AUTH_EXPIRED",
            Self::InvalidMessage => "REALTIME_INVALID_MESSAGE",
            Self::UnsupportedMessage => "REALTIME_UNSUPPORTED_MESSAGE",
            Self::HeartbeatTimeout => "REALTIME_HEARTBEAT_TIMEOUT",
            Self::Backpressure => "REALTIME_BACKPRESSURE",
            Self::SendFailed => "REALTIME_SEND_FAILED",
            Self::Internal => "REALTIME_INTERNAL_ERROR",
        }
    }

    /// Safe public message that avoids sensitive request details.
    pub fn message(self) -> &'static str {
        match self {
            Self::AuthMissing => "Authentication is required.",
            Self::AuthExpired => "Authentication has expired.",
            Self::InvalidMessage => "Message must use the standard realtime envelope.",
            Self::UnsupportedMessage => "Realtime message is not supported.",
            Self::HeartbeatTimeout => "Realtime connection heartbeat timed out.",
            Self::Backpressure => "Realtime connection is temporarily overloaded.",
            Self::SendFailed => "Realtime message could not be delivered.",
            Self::Internal => "Realtime service encountered an internal error.",
        }
    }

    /// Whether retrying without re-authentication may succeed.
    pub fn recoverable(self) -> bool {
        match self {
            Self::AuthMissing | Self::AuthExpired => false,
            Self::InvalidMessage => true,
            Self::UnsupportedMessage => true,
            Self::HeartbeatTimeout => false,
            Self::Backpressure => true,
            Self::SendFailed | Self::Internal => false,
        }
    }

    /// Structured public details for the error.
    pub fn details(self) -> serde_json::Value {
        match self {
            Self::InvalidMessage => serde_json::json!({
                "expected": r#"{ "name": "event-name", "data": {...} }"#,
            }),
            Self::AuthMissing
            | Self::AuthExpired
            | Self::UnsupportedMessage
            | Self::HeartbeatTimeout
            | Self::Backpressure
            | Self::SendFailed
            | Self::Internal => serde_json::json!({}),
        }
    }

    /// Convert this error into a realtime error WebSocket event.
    pub fn into_event(self) -> aionui_api_types::WebSocketMessage<serde_json::Value> {
        aionui_api_types::WebSocketMessage::new(
            "realtime.error",
            serde_json::json!({
                "code": self.code(),
                "message": self.message(),
                "recoverable": self.recoverable(),
                "details": self.details(),
            }),
        )
    }
}

/// Per-connection client state maintained by the server.
pub struct ClientInfo {
    /// The JWT token this connection authenticated with.
    pub token: String,
    /// Timestamp of last ping/pong activity.
    pub last_ping: Instant,
    /// Sender for outbound messages to this connection.
    pub tx: mpsc::Sender<WsOutbound>,
}

/// Server sends ping every 30 seconds.
pub const HEARTBEAT_INTERVAL: Duration = Duration::from_secs(30);

/// Connection is dropped if no pong received within 60 seconds.
pub const HEARTBEAT_TIMEOUT: Duration = Duration::from_secs(60);

/// Bounded capacity of the per-connection outbound message channel.
pub const PER_CONNECTION_BUFFER: usize = 64;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn connection_id_display() {
        let id = ConnectionId(42);
        assert_eq!(id.to_string(), "conn-42");
    }

    #[test]
    fn connection_id_equality() {
        assert_eq!(ConnectionId(1), ConnectionId(1));
        assert_ne!(ConnectionId(1), ConnectionId(2));
    }

    #[test]
    fn connection_id_hash() {
        use std::collections::HashSet;
        let mut set = HashSet::new();
        set.insert(ConnectionId(1));
        set.insert(ConnectionId(2));
        set.insert(ConnectionId(1));
        assert_eq!(set.len(), 2);
    }

    #[test]
    fn ws_outbound_text() {
        let msg = WsOutbound::Text("hello".into());
        assert_eq!(msg, WsOutbound::Text("hello".into()));
    }

    #[test]
    fn ws_outbound_close() {
        let msg = WsOutbound::Close(WebSocketCloseCode::PolicyViolation, "policy violation".into());
        assert_eq!(
            msg,
            WsOutbound::Close(WebSocketCloseCode::PolicyViolation, "policy violation".into())
        );
    }

    #[test]
    fn close_code_values() {
        assert_eq!(WebSocketCloseCode::NormalClosure.as_u16(), 1000);
        assert_eq!(WebSocketCloseCode::PolicyViolation.as_u16(), 1008);
    }

    #[test]
    fn constants() {
        assert_eq!(HEARTBEAT_INTERVAL, Duration::from_secs(30));
        assert_eq!(HEARTBEAT_TIMEOUT, Duration::from_secs(60));
        assert_eq!(PER_CONNECTION_BUFFER, 64);
    }

    #[test]
    fn realtime_invalid_message_event_uses_standard_envelope() {
        let msg = RealtimeError::InvalidMessage.into_event();
        assert_eq!(msg.name, "realtime.error");
        assert_eq!(msg.data["code"], "REALTIME_INVALID_MESSAGE");
        assert_eq!(msg.data["recoverable"], true);
        assert!(msg.data["details"]["expected"].is_string());
    }

    #[test]
    fn realtime_auth_expired_is_not_recoverable() {
        let msg = RealtimeError::AuthExpired.into_event();
        assert_eq!(msg.name, "realtime.error");
        assert_eq!(msg.data["code"], "REALTIME_AUTH_EXPIRED");
        assert_eq!(msg.data["recoverable"], false);
    }

    #[test]
    fn realtime_auth_missing_is_not_recoverable() {
        let msg = RealtimeError::AuthMissing.into_event();
        assert_eq!(msg.data["code"], "REALTIME_AUTH_MISSING");
        assert_eq!(msg.data["recoverable"], false);
    }

    #[test]
    fn realtime_boundary_error_matrix_uses_canonical_codes() {
        let cases = [
            (RealtimeError::UnsupportedMessage, "REALTIME_UNSUPPORTED_MESSAGE", true),
            (RealtimeError::HeartbeatTimeout, "REALTIME_HEARTBEAT_TIMEOUT", false),
            (RealtimeError::Backpressure, "REALTIME_BACKPRESSURE", true),
            (RealtimeError::SendFailed, "REALTIME_SEND_FAILED", false),
            (RealtimeError::Internal, "REALTIME_INTERNAL_ERROR", false),
        ];

        for (error, code, recoverable) in cases {
            let msg = error.into_event();
            assert_eq!(msg.name, "realtime.error");
            assert_eq!(msg.data["code"], code);
            assert_eq!(msg.data["recoverable"], recoverable);
            assert!(msg.data["message"].is_string());
            assert!(msg.data["details"].is_object());
        }
    }
}
