/** Fixed relative paths for the allowlisted enterprise cloud API operations. */
export const ENTERPRISE_API_ROUTES = Object.freeze({
  'company.list': 'cloud-api/CompanyController/getQiYeMaCompanyCatalogList',
  'company.detail': 'cloud-api/CompanyController/getDetailcompany',
  'company.batchGet': 'cloud-api/CompanyController/getQiYeMaCompanyBatch',
  'company.industries': 'cloud-api/CompanyController/getQiYeMaIndustryOptions',
  'product.list': 'cloud-api/CompanyController/getFindProducts',
  'product.detail': 'cloud-api/CompanyController/FindProduct',
  'catalogAssistant.plan': 'cloud-api/CatalogAiAssistantController/plan',
  'catalogAssistant.rank': 'cloud-api/CatalogAiAssistantController/rank',
  'catalogAssistant.workflowPlan': 'cloud-api/CatalogAiAssistantController/workflow-plan',
  'catalogAssistant.workflowRank': 'cloud-api/CatalogAiAssistantController/workflow-rank',
  'enterpriseAssistant.plan': 'cloud-api/EnterpriseAiAssistantController/plan',
  'project.dashboard': 'cloud-api/OpportunityController/getAiMaterialDashboard',
  'project.drill': 'cloud-api/OpportunityController/getAiMaterialDrillList',
  'project.filterOptions': 'cloud-api/OpportunityController/getAiMaterialFilterOptions',
  'project.list': 'cloud-api/OpportunityController/getAiMaterialProjectList',
  'project.detail': 'cloud-api/OpportunityController/getAiMaterialProjectDetail',
  'contact.acquire': 'cloud-api/DesktopContactController/acquire',
  'project.contactUnlock': 'cloud-api/OpportunityController/unlockAiMaterialProjectDetail',
  'demand.types': 'cloud-api/DemandQueryController/types',
  'demand.list': 'cloud-api/DemandQueryController/list',
  'demand.detail': 'cloud-api/DemandQueryController/detail',
  'demand.contactStatus': 'cloud-api/DemandContactController/status',
  'demand.contactAcquire': 'cloud-api/DemandContactController/acquire',
  'demand.publishTypes': 'cloud-api/DemandPublishController/types',
  'demand.publishSchema': 'cloud-api/DemandPublishController/schema',
  'demand.aiParse': 'cloud-api/DemandPublishController/parse',
  'demand.aiConversation.start': 'cloud-api/DemandAiConversationController/start',
  'demand.aiConversation.turn': 'cloud-api/DemandAiConversationController/turn',
  'demand.aiConversation.confirmLine': 'cloud-api/DemandAiConversationController/confirm-line',
  'demand.aiConversation.patch': 'cloud-api/DemandAiConversationController/patch',
  'demand.aiConversation.resume': 'cloud-api/DemandAiConversationController/resume',
  'demand.aiConversation.cancel': 'cloud-api/DemandAiConversationController/cancel',
  'demand.aiConversation.complete': 'cloud-api/DemandAiConversationController/complete',
  'demand.publish': 'cloud-api/DemandPublishController/publish',
  'demand.uploadImage': 'cloud-api/DemandPublishController/image/upload',
  'behavior.log': 'cloud-api/DesktopBehaviorLogController/save',
  'unified.suggest': 'cloud-api/DesktopUnifiedSearchController/suggest',
  'unified.search': 'cloud-api/DesktopUnifiedSearchController/search',
  'desktopAi.defaultConfig': 'cloud-api/DesktopAiModelController/defaultConfig',
  'auth.create': 'cloud-api/CommonWxGZHQrCodeLogIn/desktop/create',
  'auth.poll': 'cloud-api/CommonWxGZHQrCodeLogIn/desktop/poll',
  'auth.userContext': 'cloud-api/DesktopEnterpriseController/userContext',
} as const);

export type EnterpriseApiRouteKey = keyof typeof ENTERPRISE_API_ROUTES;
