/**
 * Stable identities for the desktop shell.
 *
 * Keep the operating-system identity separate from the shorter "链辽AI"
 * feature name used inside the AI workspace. Storage directories and legacy
 * protocol names are also deliberately independent from the display name.
 */
export const DESKTOP_PRODUCT_NAME = '链上辽宁·产业云城 AI桌面平台';
export const DESKTOP_PACKAGE_NAME = 'lianliao-ai-pc';
export const DESKTOP_APP_ID = 'com.lianliao.app';

/** Primary protocol generated by current versions of the desktop app. */
export const PRIMARY_PROTOCOL_SCHEME = 'lianliao';

/** Historical protocols accepted so existing links continue to work. */
export const LEGACY_PROTOCOL_SCHEMES = ['aionui'] as const;

export const SUPPORTED_PROTOCOL_SCHEMES = [PRIMARY_PROTOCOL_SCHEME, ...LEGACY_PROTOCOL_SCHEMES] as const;

export type SupportedProtocolScheme = (typeof SUPPORTED_PROTOCOL_SCHEMES)[number];
