import { z } from 'zod';

import { ENTERPRISE_LOGIN_STATUSES, ENTERPRISE_PROJECT_DRILL_LEVELS } from './constants';

const scalarSchema = z.union([z.string(), z.number(), z.boolean()]).nullish();
const positiveIntegerSchema = z.number().int().positive();
const nonNegativeIntegerSchema = z.number().int().nonnegative();
const requestIdentifierSchema = z.string().trim().min(1);

const scalarShape = <const Keys extends readonly string[]>(keys: Keys) =>
  Object.fromEntries(keys.map((key) => [key, scalarSchema])) as {
    [Key in Keys[number]]: typeof scalarSchema;
  };

const passthroughScalarSchema = <const Keys extends readonly string[]>(keys: Keys) =>
  z.object(scalarShape(keys)).passthrough();

export const commonResultSchema = z
  .object({
    success: z.literal(true),
    data: z.unknown(),
    message: z.string().optional(),
    code: z.union([z.string(), z.number()]).optional(),
  })
  .passthrough();

export const enterpriseLoginStatusSchema = z.enum(ENTERPRISE_LOGIN_STATUSES);

export const enterpriseCompanyRawSchema = passthroughScalarSchema([
  'id',
  'ID',
  'companyId',
  'COMPANY_ID',
  'name',
  'NAME',
  'companyName',
  'COMPANY_NAME',
  'shortName',
  'SHORT_NAME',
  'industry',
  'INDUSTRY',
  'city',
  'CITY',
  'district',
  'DISTRICT',
  'address',
  'ADDRESS',
  'corporation',
  'CORPORATION',
  'legalRepresentative',
  'LEGAL_REPRESENTATIVE',
  'comType',
  'COM_TYPE',
  'companyType',
  'COMPANY_TYPE',
  'comLevel',
  'COM_LEVEL',
  'companyLevel',
  'COMPANY_LEVEL',
  'vip',
  'VIP',
  'payVip',
  'PAY_VIP',
  'foundTime',
  'FOUND_TIME',
  'establishedAt',
  'ESTABLISHED_AT',
  'isCollect',
  'IS_COLLECT',
  'collected',
  'COLLECTED',
  'tempPic',
  'TEMP_PIC',
  'logoUrl',
  'LOGO_URL',
  'comAbs',
  'COM_ABS',
  'comIntro',
  'COM_INTRO',
  'description',
  'DESCRIPTION',
  'societyCode',
  'SOCIETY_CODE',
  'unifiedSocialCreditCode',
  'UNIFIED_SOCIAL_CREDIT_CODE',
  'contactPerson',
  'CONTACT_PERSON',
  'contactName',
  'CONTACT_NAME',
  'contactDuty',
  'CONTACT_DUTY',
  'contactTitle',
  'CONTACT_TITLE',
  'phone',
  'PHONE',
] as const);

export const enterpriseProductRawSchema = passthroughScalarSchema([
  'id',
  'ID',
  'productId',
  'PRODUCT_ID',
  'productsName',
  'PRODUCTS_NAME',
  'productName',
  'PRODUCT_NAME',
  'name',
  'NAME',
  'companyId',
  'COMPANY_ID',
  'companyName',
  'COMPANY_NAME',
  'tempPic',
  'TEMP_PIC',
  'imageUrl',
  'IMAGE_URL',
  'productAbs',
  'PRODUCT_ABS',
  'summary',
  'SUMMARY',
  'industry',
  'INDUSTRY',
  'compIndustry',
  'COMP_INDUSTRY',
  'city',
  'CITY',
  'compCity',
  'COMP_CITY',
  'district',
  'DISTRICT',
  'compDistrict',
  'COMP_DISTRICT',
  'address',
  'ADDRESS',
  'compAddress',
  'COMP_ADDRESS',
  'compContactPerson',
  'COMP_CONTACT_PERSON',
  'contactName',
  'CONTACT_NAME',
  'compPhone',
  'COMP_PHONE',
  'phone',
  'PHONE',
  'isCollect',
  'IS_COLLECT',
  'collected',
  'COLLECTED',
] as const);

export const enterpriseProjectRawSchema = passthroughScalarSchema([
  'id',
  'ID',
  'hpInfoId',
  'HP_INFO_ID',
  'dbId',
  'DB_ID',
  'projectName',
  'PROJECT_NAME',
  'name',
  'NAME',
  'title',
  'TITLE',
  'constructionUnit',
  'CONSTRUCTION_UNIT',
  'ownerName',
  'OWNER_NAME',
  'danwei',
  'DANWEI',
  'province',
  'PROVINCE',
  'sheng',
  'SHENG',
  'city',
  'CITY',
  'region',
  'REGION',
  'totalInvestment',
  'TOTAL_INVESTMENT',
  'zongtouzi',
  'ZONGTOUZI',
  'constructionNature',
  'CONSTRUCTION_NATURE',
  'xingzhi',
  'XINGZHI',
  'investmentType',
  'INVESTMENT_TYPE',
  'projectNature',
  'PROJECT_NATURE',
  'xiangmuxingzhi',
  'XIANGMUXINGZHI',
  'publishDate',
  'PUBLISH_DATE',
  'inputTime',
  'INPUT_TIME',
  'constructionPeriod',
  'CONSTRUCTION_PERIOD',
  'buildCycleText',
  'BUILD_CYCLE_TEXT',
  'jianshezhouqi',
  'JIANSHEZHOUQI',
  'startDate',
  'START_DATE',
  'endDate',
  'END_DATE',
  'materialName',
  'MATERIAL_NAME',
  'materialShortName',
  'MATERIAL_SHORT_NAME',
  'procurementSummary',
  'PROCUREMENT_SUMMARY',
  'lianxiren',
  'LIANXIREN',
  'contactName',
  'CONTACT_NAME',
  'phone',
  'PHONE',
  'email',
  'EMAIL',
  'address',
  'ADDRESS',
  'didian',
  'DIDIAN',
  'buildLocation',
  'BUILD_LOCATION',
  'industry',
  'INDUSTRY',
  'hangye',
  'HANGYE',
  'landArea',
  'LAND_AREA',
  'zhandimianji',
  'ZHANDIMIANJI',
  'buildingArea',
  'BUILDING_AREA',
  'jianzhumianji',
  'JIANZHUMIANJI',
  'greenArea',
  'GREEN_AREA',
  'lvhualv',
  'LVHUALV',
  'constructionScale',
  'CONSTRUCTION_SCALE',
  'guimo',
  'GUIMO',
  'equipment',
  'EQUIPMENT',
  'shebeigouzhi',
  'SHEBEIGOUZHI',
  'materials',
  'MATERIALS',
  'yuancailiao',
  'YUANCAILIAO',
  'projectComposition',
  'PROJECT_COMPOSITION',
  'jianshezucheng',
  'JIANSHEZUCHENG',
  'sourceUrl',
  'SOURCE_URL',
  'reqUrl',
  'REQ_URL',
  'isCollect',
  'IS_COLLECT',
  'collected',
  'COLLECTED',
  'followStatus',
  'FOLLOW_STATUS',
  'isPurchased',
  'IS_PURCHASED',
  'purchased',
  'PURCHASED',
] as const);

export const enterprisePageRawSchema = z
  .object({
    list: z.array(z.unknown()).optional(),
    LIST: z.array(z.unknown()).optional(),
    rows: z.array(z.unknown()).optional(),
    ROWS: z.array(z.unknown()).optional(),
    pageNum: scalarSchema,
    PAGE_NUM: scalarSchema,
    pageSize: scalarSchema,
    PAGE_SIZE: scalarSchema,
    pages: scalarSchema,
    PAGES: scalarSchema,
    total: scalarSchema,
    TOTAL: scalarSchema,
  })
  .passthrough();

export const enterpriseDistributionRawSchema = passthroughScalarSchema([
  'name',
  'NAME',
  'label',
  'LABEL',
  'value',
  'VALUE',
  'dimension',
  'DIMENSION',
  'budgetRange',
  'BUDGET_RANGE',
  'projectCount',
  'PROJECT_COUNT',
] as const);

const enterpriseDashboardKpiRawSchema = passthroughScalarSchema([
  'projectCount',
  'PROJECT_COUNT',
  'categoryL1Count',
  'CATEGORY_L1_COUNT',
  'categoryL2Count',
  'CATEGORY_L2_COUNT',
  'shortNameCount',
  'SHORT_NAME_COUNT',
  'materialShortNameCount',
  'MATERIAL_SHORT_NAME_COUNT',
  'materialNameCount',
  'MATERIAL_NAME_COUNT',
  'investmentTotalYi',
  'INVESTMENT_TOTAL_YI',
] as const);

export const enterpriseDashboardRawSchema = passthroughScalarSchema([
  'runId',
  'RUN_ID',
  'updatedAt',
  'UPDATED_AT',
  'projectCount',
  'PROJECT_COUNT',
  'categoryL1Count',
  'CATEGORY_L1_COUNT',
  'categoryL2Count',
  'CATEGORY_L2_COUNT',
  'shortNameCount',
  'SHORT_NAME_COUNT',
  'materialShortNameCount',
  'MATERIAL_SHORT_NAME_COUNT',
  'materialNameCount',
  'MATERIAL_NAME_COUNT',
  'investmentTotalYi',
  'INVESTMENT_TOTAL_YI',
] as const).extend({
  kpi: enterpriseDashboardKpiRawSchema.optional(),
  regionDistribution: z.array(enterpriseDistributionRawSchema).optional(),
  REGION_DISTRIBUTION: z.array(enterpriseDistributionRawSchema).optional(),
  budgetDistribution: z.array(enterpriseDistributionRawSchema).optional(),
  BUDGET_DISTRIBUTION: z.array(enterpriseDistributionRawSchema).optional(),
  categoryDistribution: z.array(enterpriseDistributionRawSchema).optional(),
  CATEGORY_DISTRIBUTION: z.array(enterpriseDistributionRawSchema).optional(),
  shortNameTop: z.array(enterpriseDistributionRawSchema).optional(),
  SHORT_NAME_TOP: z.array(enterpriseDistributionRawSchema).optional(),
  materialTop: z.array(enterpriseDistributionRawSchema).optional(),
  MATERIAL_TOP: z.array(enterpriseDistributionRawSchema).optional(),
});

export const enterpriseDrillRawSchema = passthroughScalarSchema([
  'name',
  'NAME',
  'label',
  'LABEL',
  'level',
  'LEVEL',
  'resultLevel',
  'RESULT_LEVEL',
  'categoryL1',
  'CATEGORY_L1',
  'categoryL2',
  'CATEGORY_L2',
  'materialShortName',
  'MATERIAL_SHORT_NAME',
  'materialName',
  'MATERIAL_NAME',
  'categoryL2Count',
  'CATEGORY_L2_COUNT',
  'shortNameCount',
  'SHORT_NAME_COUNT',
  'materialShortNameCount',
  'MATERIAL_SHORT_NAME_COUNT',
  'materialNameCount',
  'MATERIAL_NAME_COUNT',
  'projectCount',
  'PROJECT_COUNT',
] as const);

export const userContextRawSchema = passthroughScalarSchema([
  'registered',
  'REGISTERED',
  'openId',
  'OPEN_ID',
  'openid',
  'OPENID',
  'userId',
  'USER_ID',
  'id',
  'ID',
  'userName',
  'USER_NAME',
  'companyId',
  'COMPANY_ID',
  'companyName',
  'COMPANY_NAME',
  'companyLevel',
  'COMPANY_LEVEL',
  'comLevel',
  'COM_LEVEL',
  'roleId',
  'ROLE_ID',
] as const);

const companyListQuerySchema = z
  .object({
    keyword: z.string().optional(),
    industry: z.string().optional(),
    city: z.string().optional(),
    district: z.string().optional(),
    contactState: z.enum(['CONTACTED', 'UNCONTACTED']).optional(),
    pageNum: positiveIntegerSchema,
    pageSize: positiveIntegerSchema,
  })
  .strict();

const productListQuerySchema = z
  .object({
    keyword: z.string().optional(),
    industry: z.string().optional(),
    companyId: requestIdentifierSchema.optional(),
    parkId: z.string().optional(),
    sort: z.string().optional(),
    pageNum: positiveIntegerSchema,
    pageSize: positiveIntegerSchema,
  })
  .strict();

const projectDrillQuerySchema = z
  .object({
    level: z.enum(ENTERPRISE_PROJECT_DRILL_LEVELS),
    runId: z.string().optional(),
    province: z.string().optional(),
    city: z.string().optional(),
    budgetRange: z.string().optional(),
    categoryL1: z.string().optional(),
    categoryL2: z.string().optional(),
    materialShortName: z.string().optional(),
    materialName: z.string().optional(),
    minProjectCount: nonNegativeIntegerSchema.optional(),
  })
  .strict();

const projectListQuerySchema = z
  .object({
    keyword: z.string().optional(),
    runId: z.string().optional(),
    categoryL1: z.string().optional(),
    categoryL2: z.string().optional(),
    materialShortName: z.string().optional(),
    materialName: z.string().optional(),
    province: z.string().optional(),
    city: z.string().optional(),
    budgetRange: z.string().optional(),
    constructionNature: z.string().optional(),
    investmentType: z.string().optional(),
    publishedFrom: z.string().optional(),
    publishedTo: z.string().optional(),
    pageNum: positiveIntegerSchema,
    pageSize: positiveIntegerSchema,
  })
  .strict();

export const enterpriseRequestSchema = z.discriminatedUnion('operation', [
  z.object({ operation: z.literal('company.list'), payload: companyListQuerySchema }).strict(),
  z
    .object({
      operation: z.literal('company.detail'),
      payload: z.object({ companyId: requestIdentifierSchema }).strict(),
    })
    .strict(),
  z.object({ operation: z.literal('product.list'), payload: productListQuerySchema }).strict(),
  z
    .object({
      operation: z.literal('product.detail'),
      payload: z.object({ productId: requestIdentifierSchema }).strict(),
    })
    .strict(),
  z
    .object({
      operation: z.literal('project.dashboard'),
      payload: z.object({ runId: z.string().optional() }).strict(),
    })
    .strict(),
  z.object({ operation: z.literal('project.drill'), payload: projectDrillQuerySchema }).strict(),
  z.object({ operation: z.literal('project.list'), payload: projectListQuerySchema }).strict(),
  z
    .object({
      operation: z.literal('project.detail'),
      payload: z.object({ hpInfoId: requestIdentifierSchema }).strict(),
    })
    .strict(),
]);
