pub mod agent;
mod agent_close;
pub mod agent_event_tracker;
pub mod agent_reconcile;
mod agent_session_flow;
pub mod catalog_forwarder;
pub(crate) mod config_option_catalog;
pub(crate) mod config_options;
mod error_mapping;
pub mod hooks;
pub(crate) mod mode_normalize;
pub mod permission_router;
pub mod session;
mod stderr_error_extractor;

pub use agent::AcpAgentManager;
pub use agent_event_tracker::AcpSessionEvent;
pub use agent_reconcile::ReconcileAction;
pub use catalog_forwarder::CatalogForwarder;
pub use hooks::SessionNewPreludeHook;
pub use permission_router::PermissionRouter;
pub use session::AcpSession;
